# Generated by Django 5.1.6 on 2025-11-02 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('child', 'Child'), ('maternal', 'Maternal')], max_length=10)),
                ('reference_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('taken', models.BooleanField(default=False)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khop.vaccine')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khop.userschedule')),
            ],
        ),
    ]
